<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="model.syncManager.UserSyncManagerImplTest" tests="4" skipped="0" failures="0" errors="0" timestamp="2017-11-26T10:36:40" hostname="rexmint" time="0.087">
  <properties/>
  <testcase name="testA" classname="model.syncManager.UserSyncManagerImplTest" time="0.016"/>
  <testcase name="testB" classname="model.syncManager.UserSyncManagerImplTest" time="0.029"/>
  <testcase name="testC" classname="model.syncManager.UserSyncManagerImplTest" time="0.011"/>
  <testcase name="testD" classname="model.syncManager.UserSyncManagerImplTest" time="0.031"/>
  <system-out><![CDATA[javax.validation.ConstraintViolationException: Bean Validation constraint(s) violated while executing Automatic Bean Validation on callback event:'prePersist'. Please refer to embedded ConstraintViolations for details.
]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
